apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: graphviz
    tier: frontend
spec:
  replicas: 3
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #  app: graphviz
  #  tier: frontend
  template:
    metadata:
      labels:
        app: graphviz
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: gcr.io/gdg-apps-1090/graphviz-webapp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
          hostPort: 80
